env:
  browser: true
  commonjs: true
  es6: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  "indent": ["error", 4],
  "space-before-function-paren": ["error", "never"],
  "semi": ["error", "always"]
}
